// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kkslhmagkyoujwxgfaha.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtrc2xobWFna3lvdWp3eGdmYWhhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3MjU3OTMsImV4cCI6MjA2MjMwMTc5M30.2O-Df2D6ZuOUZZnU-Uze8S4w4_7s3-gv7sJhMX_urjc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);